# Generated by Django 2.1.1 on 2018-09-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnapAnimations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=100)),
                ('easing', models.CharField(choices=[('linear', 'linear'), ('easein', 'easein'), ('easeout', 'easeout'), ('easeinout', 'easeinout'), ('backin', 'backin'), ('backout', 'backout'), ('bounce', 'bounce'), ('elastic', 'elastic')], max_length=10)),
                ('transition_time', models.IntegerField(default=500)),
                ('init_state', models.TextField(blank=True)),
            ],
        ),
    ]
